# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
images:
  defaultbackend:
    repository: gcr.io/google_containers/defaultbackend
    tag: "1.0"
    pullPolicy: IfNotPresent
  nginxIngress:
    repository: gcr.io/google_containers/nginx-ingress-controller
    tag: "0.9.0-beta.15"
    pullPolicy: IfNotPresent

application:
  track: stable
  tier: web

service:
  name: nginx
  type: ClusterIP
  containerPort: 5082
  internalPort: 5901
  ports:
  - http: 5901

proxyConnectTimeout: 15
proxyReadTimeout: 600
proxySendTimeout: 600
proxyBodySize: "512m"
hstsIncludeSubdomains: false
serverNameHashBucketSize: 256

shell:
  name: omnibus
  port: og-shell

resources: {}
  limits:
   cpu: 100m
   memory: 96Mi
  requests:
   cpu: 50m
   memory: 32Mi
