apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
    spec:
      hostname: {{ .Chart.Name }}
      imagePullSecrets:
        - name: gitlab-registry
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PROXYLIST
          valueFrom:
            secretKeyRef:
              name: proxypool-secrets
              key: proxylist
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: proxypool-secrets
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: proxypool-secrets
              key: redis-port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: proxypool-secrets
              key: redis-password
        - name: STATSD_HOST
          valueFrom:
            secretKeyRef:
              name: proxypool-secrets
              key: statsd-host
              optional: true
        - name: ALERT_MANAGER
          valueFrom:
            secretKeyRef:
              name: proxypool-secrets
              key: alert-manager
              optional: true
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: portfolio-secrets
              key: environment
              optional: true
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5901
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5901
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
{{ toYaml .Values.resources | indent 12 }}
